# Generated by Django 4.2.7 on 2024-01-05 08:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('none', 'None'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=20)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('city', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=120)),
                ('pincode', models.CharField(default='', max_length=6)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_image', models.ImageField(upload_to='event_images')),
                ('description', models.TextField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ticket_price', models.PositiveIntegerField()),
                ('slots_available', models.PositiveIntegerField(null=True)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('focus', models.CharField(choices=[('none', 'None'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('event_organizer', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventapp.eventorganizer')),
            ],
        ),
    ]
