# Generated by Django 4.2.7 on 2024-02-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_ticketbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='slug',
            field=models.SlugField(max_length=8, null=True, unique=True),
        ),
    ]
