# Generated by Django 4.2.7 on 2024-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_ticketbooking_total_alter_ticketbooking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='slots',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
