# Generated by Django 4.0 on 2024-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_ticketbooking_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
