# Generated by Django 4.0 on 2024-02-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_ticketbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='valid',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
